### ISSUE TITLE
cannot get Eufy 11C to be seen in home assistant

### ISSUE THREAD

**Issue by smeg1** [3ative/Eufy-RoboVac-to-HA#1]
Hi I have followed the steps all good but cannot get Eufy 11C to be seen in home assistant here's the details, I thought the 11C would work as its wifi enabled

EufyHome_2.4.0_vevs
MAC address "58:XX:XX:XX:XX:XX”
IP-address: 192.168.0.XXX
Local code: XXXXCF446583XXXX
Device ID: 549eXXXX-XXXX-XXXX-XXXX-17cca472XXXX
Device key: XXXX095C010EXXXX
<img width="752" alt="Screenshot 2021-12-02 at 2 23 26 pm" src="https://user-images.githubusercontent.com/24874296/144441599-c7fd9462-6c14-44a9-87fd-0aa529044512.png">

**Comment by 3ative** [comment]
Hi, 
I got a notification, on YouTube, about your comment but, couldn't find it to reply to.

I am unable to test other vacuum models however, as everything 'worked' for you so far, try changing the type code to "T2118":

```yaml
eufy_vacuum:
  devices:
    - name: xxx
      address: xxxx
      access_token: xxxxx
      id: xxxx
      type: T2118 ## Trying using this code instead
```

It maybe the Home Assistant integration not recognising other EUFY models.
